# Generated by Django 6.0.6 on 2026-06-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('ml', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml.mlmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['asset', 'prediction_time'], name='ml_predicti_asset_i_42b851_idx'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['model', 'prediction_time'], name='ml_predicti_model_i_4edcad_idx'),
        ),
    ]
