# Generated by Django 6.0.6 on 2026-06-14 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alarm_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert'), ('trip', 'Trip')], max_length=10)),
                ('message', models.TextField()),
                ('value_at_alarm', models.FloatField(blank=True, null=True)),
                ('threshold_breached', models.FloatField(blank=True, null=True)),
                ('iso_standard_ref', models.CharField(blank=True, max_length=50)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts_alarm_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
