# Generated by Django 6.0.6 on 2026-06-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='sensor_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='assets.sensordefinition'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['asset', 'severity', 'created_at'], name='alerts_alar_asset_i_a41103_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['acknowledged', 'created_at'], name='alerts_alar_acknowl_967b4e_idx'),
        ),
    ]
