"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { ArrowLeft, Search, Terminal, FileText, Calendar, FileDown, FileCode, Maximize2, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import ClickSpark from "@/animations/ClickSpark";
import { getMaintenanceLogs } from "@/services/maintenance";
import type { MaintenanceLog } from "@/services/types";

const problemStatementMd = `# AI Hackathon | Round 2 - Agentic AI Challenge | Problem Statement

## 1. Background
Steel manufacturing plants operate highly complex, capital-intensive, and interdependent equipment systems. Any unplanned downtime in such environments can result in production loss, safety risks, operational inefficiencies, and increased maintenance costs. In practice, maintenance engineers often rely on multiple fragmented information sources—such as equipment manuals, standard operating procedures (SOPs), historical maintenance logs, failure analysis reports, and sensor-based alerts—to identify equipment issues and determine appropriate corrective action. This process is typically manual, time-consuming, and dependent on expert judgement, which can delay response times and reduce consistency in maintenance decisions. There is a clear need for an intelligent, context-aware maintenance support system that can consolidate diverse data sources, assist in diagnosis, improve root cause analysis, recommend prioritized maintenance actions, and enable predictive maintenance for critical industrial assets.

## 2. Objective
The objective of this problem statement is to design and develop an intelligent Maintenance Wizard for industrial equipment in steel manufacturing environments. The proposed system should act as a decision-support platform for maintenance engineers by enabling:
- Faster and more accurate diagnosis of equipment issues
- Identification of probable root causes of failures
- Prediction of equipment degradation and remaining useful life
- Proactive detection of abnormalities and catastrophic failure risks
- Prioritization of maintenance actions based on operational and procurement constraints
- Generation of structured maintenance insights and reports

The solution should support both reactive troubleshooting and proactive maintenance planning, thereby improving plant reliability, reducing downtime, and enhancing maintenance efficiency.

## 3. Problem Description
Participants are required to build a system that can ingest maintenance-related inputs from multiple sources and provide explainable, actionable, and structured outputs for maintenance decision-making. The system should be capable of analysing equipment conditions, identifying abnormalities, assessing risk levels, recommending immediate and long-term maintenance actions, and assisting users through natural language interaction. The proposed solution should also support learning from historical data and engineer feedback, enabling continuous improvement in recommendations and predictions over time.

## 4. Expected Inputs
The system should accept one or more of the following input types:

### 4.1 Operational and Failure Inputs
- Equipment delay logs
- Fault/error messages generated by equipment or control systems
- Failure analysis reports
- Incident records and historical breakdown summaries

### 4.2 Condition Monitoring Inputs
- Sensor data summaries
- Abnormality or anomaly alerts
- Process condition indicators relevant to equipment health

### 4.3 Knowledge and Documentation Inputs
- Equipment manuals
- Maintenance SOPs
- Historical maintenance records
- Spare parts information, including availability and procurement lead time

### 4.4 User Interaction Inputs
- Natural language queries from maintenance engineers
- Scenario-based learning or troubleshooting prompts
- Follow-up queries in a multi-turn conversational format

## 5. Expected Outputs
The system should generate clear, structured, and explainable outputs, including but not limited to the following:

### 5.1 Diagnostic and Predictive Outputs
- Probable fault diagnosis
- Root cause analysis of failures or abnormal conditions
- Prediction of remaining lifecycle / remaining useful life (RUL) of equipment or systems
- Early warning of potential catastrophic failures in critical equipment
- Detection of process-related defects contributing to equipment issues

### 5.2 Risk and Priority Outputs
- Risk level classification (e.g., low, medium, high, critical)
- Urgency assessment for intervention
- Bottleneck prioritization at the plant level
- Prioritization based on:
  - process criticality
  - delay severity
  - spares availability
  - procurement lead time

### 5.3 Maintenance Recommendation Outputs
- Step-by-step maintenance or repair recommendations
- Immediate action points
- Optimized maintenance plan
- Long-term monitoring recommendations
- Spare procurement strategy, where applicable

### 5.4 Reporting Outputs
- Structured maintenance reports
- Abnormal alert reports
- Maintenance decision summaries for engineers and supervisors
- Equipment-specific digital maintenance log entries (optional enhancement)

## 6. Functional Requirements
The proposed system should meet the following functional requirements:

### 1. Contextual Reasoning Using LLMs or SLMs
The solution should integrate Large Language Models (LLMs) or Small Language Models (SLMs) for contextual understanding, reasoning, and maintenance query answering. Additional merit may be given to teams that create or fine-tune a domain-specific model for industrial maintenance use cases. Publicly available APIs may be used.

### 2. Knowledge Integration
The system should be capable of integrating and reasoning over:
- Equipment manuals
- Maintenance SOPs
- Historical maintenance records
- Failure reports and operational logs

### 3. Natural Language Interaction
The solution should support natural language queries from users and handle multi-turn conversations in a context-aware manner.

### 4. Explainable Recommendations
Outputs generated by the system should be explainable and traceable to relevant input data, historical records, rules, or documentation wherever possible.

### 5. Abnormality Detection and Failure Prediction
The system should include an architecture for:
- Dynamic abnormality detection
- Early warning generation
- Failure prediction for critical equipment

### 6. Feedback-Driven Improvement
The system should incorporate a feedback loop through which user corrections, confirmations, or outcomes can be used to improve future recommendations.

### 7. Real-Time Alerting Capability
The solution should be capable of generating real-time abnormal alert reports and user-specific notifications where relevant.

## 7. Optional Enhancements
Teams may additionally implement one or more of the following features to enhance the usability and practical value of the system:
- Conversational interface for maintenance engineers
- Visualization dashboard for equipment health, trends, and anomalies
- Integration with simulated IoT or equipment monitoring dashboards
- Dynamic knowledge base for each equipment or system
- Automatic digital logbook for maintenance activities and observations
- User-role-based alerts and recommendations

## 8. Expected Outcome
The final solution should function as an intelligent maintenance decision-support system that helps industrial operations teams:
- Reduce unplanned downtime
- Improve maintenance response time
- Increase diagnostic accuracy
- Shift from reactive to proactive maintenance practices
- Improve maintenance planning and spare management
- Enable faster and more informed troubleshooting in industrial environments

The system should demonstrate practical applicability in a steel plant.

## 9. Deliverables
Participants are expected to submit the following:
- Detailed Source Code of Working Prototype
  - Complete code required to run the system.
- A clear document explaining:
  - System architecture
  - Technology stack used
  - Data flow and system flow
  - Model design and reasoning pipeline
  - Alerting and prediction logic
  - Assumptions and limitations
- Documentation describing how to install, configure, and run the system
- Sample Input and Output Demonstration
- A screen recording that showcases the features that have been built

All the above deliverables may be consolidated and uploaded as a single ZIP file.`;

export default function HistoricalLogsPage() {
  const [isMobile, setIsMobile] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedModule, setSelectedModule] = useState<string>("all");
  const [activeLogId, setActiveLogId] = useState<string | null>("log-1");
  const [viewMode, setViewMode] = useState<"pdf" | "online">("pdf");
  const [expandedView, setExpandedView] = useState<"pdf" | "online" | null>(null);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth < 1024);
    };
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const logs: MaintenanceLog[] = [
    {
      id: "log-1",
      code: "MR-2024-441",
      date: "2024-11-05",
      asset: "F1-EQ09 Centrifugal Exhauster",
      module: "CokeOven-Agent",
      description: "Complete replacement of the inboard spherical roller bearing after high-frequency vibration alarms. Exchanged and aligned. Lubrication system flushed.",
      verdict: "RESOLVED - RUL reset to 365 Days",
      operator: "M. Chatterjee",
      pdfUrl: "/docs/ai_hackathon_problem_statement.pdf",
      onlineContent: problemStatementMd,
    },
    {
      id: "log-2",
      code: "MR-2024-388",
      date: "2024-09-18",
      asset: "F2-EQ04 Drive Sprocket",
      module: "Sinter-Agent",
      description: "Tooth root wear check. Manual calibration offset applied on the Sinter belt feeder speed controller. Re-greased drive coupling.",
      verdict: "MONITORING - RUL at 120 Days",
      operator: "A. Sengupta",
    },
    {
      id: "log-3",
      code: "MR-2024-301",
      date: "2024-07-22",
      asset: "F2-EQ09 Waste Gas Fan Impeller",
      module: "Sinter-Agent",
      description: "Blade wear survey. Impeller surface showing moderate pitting. Performed structural reinforcement and dynamic balancing.",
      verdict: "RESOLVED - RUL reset to 180 Days",
      operator: "R. Sharma",
    },
    {
      id: "log-4",
      code: "MR-2024-270",
      date: "2024-06-11",
      asset: "F1-EQ11 Electrostatic Precipitator",
      module: "CokeOven-Agent",
      description: "Electrode alignment inspection and high-voltage grid cleaning. Removed carbon build-up on exhaust plates. Refitted insulator bushings.",
      verdict: "RESOLVED - RUL reset to 240 Days",
      operator: "M. Chatterjee",
    },
    {
      id: "log-5",
      code: "MR-2024-192",
      date: "2024-04-03",
      asset: "F1-EQ09 Exhauster Motor",
      module: "CokeOven-Agent",
      description: "FFT baseline spectral run on stator windings. Found minor phase balance variation. Thermal imaging matches nominal reference index.",
      verdict: "NOMINAL",
      operator: "S. K. Patel",
    },
  ];

  const activeLog = logs.find(l => l.id === activeLogId) || logs[0];

  const isFirstLog = activeLog?.id === "log-1";

  const filteredLogs = logs.filter(log => {
    const matchesSearch = log.code.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          log.asset.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          log.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesModule = selectedModule === "all" || log.module === selectedModule;
    return matchesSearch && matchesModule;
  });

  return (
    <ClickSpark
      sparkColor="#f97316"
      sparkSize={8}
      sparkRadius={18}
      sparkCount={6}
      duration={350}
      className="relative min-h-screen w-full bg-[#FAF9F5] flex flex-col justify-start overflow-hidden select-none"
    >


      {isMobile ? (
        <div className="flex flex-col gap-6 w-full px-6 pt-24 pb-12 select-none max-w-lg mx-auto z-10">
          <div className="bg-white border border-zinc-200 p-6 rounded-2xl shadow-xs">
            <h1 className="text-3xl font-black text-zinc-950 tracking-tighter uppercase leading-none" style={{ fontFamily: "var(--font-pixeloid)" }}>
              SANSAD<br />HUB
            </h1>
            <p className="text-[9px] text-[#f97316] mt-3 font-bold uppercase tracking-[0.2em]">
              Historical Logs
            </p>
          </div>
          <div className="bg-white border border-zinc-200 p-6 rounded-2xl">
            <p className="text-sm text-zinc-600">Please open this page on a desktop viewport to inspect maintenance history records.</p>
            <Link href="/sansad/hub" className="mt-4 block text-center py-2 bg-[#1b253c] text-white rounded-xl text-[10px] font-bold uppercase tracking-wider">
              Back to Console
            </Link>
          </div>
        </div>
      ) : (
        <div className="w-screen h-screen overflow-hidden bg-[#FAF9F5] relative flex select-none">
          {/* Left Gutter Vertical Marquee (8vw width) */}
          <div className="absolute left-0 top-0 bottom-0 w-[8vw] overflow-hidden z-20 pointer-events-none flex flex-col justify-start border-r border-zinc-200 bg-[#FAF9F5]">
            <div className="animate-marquee-up flex flex-col items-center w-full">
              {Array(6).fill("SANSAD").concat(Array(6).fill("SANSAD")).map((text, idx) => (
                <div key={idx} className="w-full h-[33.33vh] flex items-center justify-center border-b border-zinc-200/60 py-12 pointer-events-auto">
                  <span className="atal-text-filled text-4xl lg:text-5xl xl:text-6xl tracking-wider select-none">
                    {text}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Right Gutter Vertical Marquee (8vw width) */}
          <div className="absolute right-0 top-0 bottom-0 w-[8vw] overflow-hidden z-20 pointer-events-none flex flex-col justify-start border-l border-zinc-200 bg-[#FAF9F5]">
            <div className="animate-marquee-down flex flex-col items-center w-full">
              {Array(6).fill("ATAL").concat(Array(6).fill("ATAL")).map((text, idx) => (
                <div key={idx} className="w-full h-[33.33vh] flex items-center justify-center border-b border-zinc-200/60 py-12 pointer-events-auto">
                  <span className="atal-text-filled text-4xl lg:text-5xl xl:text-6xl tracking-wider select-none">
                    {text}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Centered partitioned area spanning exactly 84vw */}
          <div className="absolute left-[8vw] w-[84vw] h-full flex flex-col bg-[#FAF9F5] p-12 overflow-y-auto scrollbar-none [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar-track]:hidden [&::-webkit-scrollbar-thumb]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
            <div className="w-full flex items-center justify-between mb-4 border-b border-zinc-200 pb-4 select-none">
              <div className="w-1/4 flex justify-start">
                <Link href="/sansad/hub" className="flex items-center select-none">
                  <div 
                    className="h-10 px-4 bg-[#1b253c] hover:bg-[#f97316] text-white rounded-xl flex items-center justify-center gap-0 hover:gap-2 transition-all duration-300 ease-out overflow-hidden group/btn cursor-pointer shadow-xs font-bold" 
                    style={{ fontFamily: "var(--font-pixeloid)" }}
                  >
                    <ArrowLeft className="w-0 h-5 text-white opacity-0 transition-all duration-300 ease-out group-hover/btn:w-5 group-hover/btn:opacity-100 shrink-0" />
                    <span className="text-xs uppercase tracking-wider">Back</span>
                  </div>
                </Link>
              </div>
              <div className="flex-1 text-center">
                <h1 className="text-4xl font-black uppercase text-zinc-950 tracking-tight" style={{ fontFamily: "var(--font-questrial)" }}>
                  HISTORICAL LOGS
                </h1>
                <span className="text-[10px] font-mono text-zinc-450 uppercase tracking-widest block mt-1">
                  SOP records & repair history index
                </span>
              </div>
              <div className="w-1/4" />
            </div>

            <div className="flex-1 flex gap-8 min-h-0">
              <div className="w-[45%] h-full flex flex-col gap-4">
                <div className="bg-white border border-zinc-200 p-4 rounded-2xl flex flex-col gap-3">
                  <div className="relative">
                    <input
                      type="text"
                      placeholder="Search log code, asset, or repair info..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="w-full bg-[#FAF9F5] border border-zinc-200 text-[#1b253c] placeholder:text-[#1b253c]/40 focus:bg-white focus:border-[#f97316] focus:ring-1 focus:ring-[#f97316] rounded-xl pl-10 pr-3 py-2.5 text-xs focus:outline-none transition-all duration-200 font-semibold"
                    />
                    <Search className="w-4 h-4 text-zinc-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                  </div>
                  <div className="flex gap-2">
                    {["all", "CokeOven-Agent", "Sinter-Agent"].map((mod) => (
                      <button
                        key={mod}
                        onClick={() => setSelectedModule(mod)}
                        className={`px-3 py-1 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-all cursor-pointer ${
                          selectedModule === mod 
                            ? "bg-[#1b253c] text-white" 
                            : "bg-[#FAF9F5] text-zinc-500 border border-zinc-200 hover:text-[#1b253c] hover:border-zinc-350"
                        }`}
                      >
                        {mod === "all" ? "All Modules" : mod}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex-1 overflow-y-auto space-y-3 pr-6 scrollbar-none [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar-track]:hidden [&::-webkit-scrollbar-thumb]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
                  {filteredLogs.length === 0 ? (
                    <div className="text-center py-12 text-sm font-mono text-zinc-400">
                      No logs match the query search parameters.
                    </div>
                  ) : (
                    filteredLogs.map((log) => {
                      const isActive = log.id === activeLogId;
                      return (
                        <div
                          key={log.id}
                          onClick={() => setActiveLogId(log.id)}
                          className={`p-5 rounded-2xl border transition-all duration-300 cursor-pointer select-none relative ${
                            isActive 
                              ? "bg-[#4A582E] border-[#4A582E] shadow-md text-white mr-1" 
                              : "bg-white border-zinc-200 hover:border-[#4A582E] mr-1"
                          }`}
                        >
                          <div className="flex justify-between items-center mb-2">
                            <span className={`font-mono text-xs font-bold uppercase tracking-widest ${isActive ? "text-zinc-200" : "text-zinc-400"}`}>{log.code}</span>
                            <span className={`font-mono text-xs ${isActive ? "text-zinc-200" : "text-[#f97316]"}`}>{log.date}</span>
                          </div>
                          <h4 className={`text-lg font-black uppercase ${isActive ? "text-white" : "text-[#1b253c]"}`} style={{ fontFamily: "var(--font-questrial)" }}>
                            {log.asset}
                          </h4>
                          <span className={`text-xs font-mono font-bold uppercase tracking-widest block mt-1 ${isActive ? "text-zinc-200" : "text-zinc-400"}`}>Module: {log.module}</span>
                        </div>
                      );
                    })
                  )}
                </div>
              </div>

              <div className="flex-1 h-full bg-white border border-zinc-200 rounded-3xl p-8 flex flex-col relative overflow-hidden">
                <div className="absolute top-2.5 left-2.5 font-mono text-[9px] text-[#1b253c]/35 select-none">+</div>
                <div className="absolute bottom-2.5 right-2.5 font-mono text-[9px] text-[#1b253c]/35 select-none">+</div>

                {activeLog && (
                  <div className="flex flex-col h-full">
                    <div className="flex justify-between items-start border-b pb-4 mb-6">
                      <div>
                        <div className="flex items-center gap-2">
                          <Terminal className="w-5 h-5 text-orange-500" />
                          <span className="font-mono text-sm font-black text-orange-500 tracking-wider">{activeLog.code}</span>
                        </div>
                        <h3 className="text-3xl font-black text-[#1b253c] uppercase mt-1" style={{ fontFamily: "var(--font-questrial)" }}>
                          {activeLog.asset}
                        </h3>
                      </div>
                      <div className="flex items-center gap-1.5 text-sm font-mono text-[#f97316] font-bold uppercase">
                        <Calendar className="w-4 h-4" />
                        {activeLog.date}
                      </div>
                    </div>

                    {isFirstLog && (
                      <div className="flex gap-3 mb-4">
                        <button
                          onClick={() => setViewMode("pdf")}
                          className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider transition-all duration-200 cursor-pointer ${
                            viewMode === "pdf"
                              ? "bg-[#1b253c] text-white shadow-md"
                              : "bg-zinc-100 text-zinc-500 hover:bg-zinc-200"
                          }`}
                        >
                          <FileDown className="w-4 h-4" />
                          View PDF
                        </button>
                        <button
                          onClick={() => setViewMode("online")}
                          className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider transition-all duration-200 cursor-pointer ${
                            viewMode === "online"
                              ? "bg-[#1b253c] text-white shadow-md"
                              : "bg-zinc-100 text-zinc-500 hover:bg-zinc-200"
                          }`}
                        >
                          <FileCode className="w-4 h-4" />
                          Online Version
                        </button>
                      </div>
                    )}

                    <div className="space-y-4 flex-1 overflow-y-auto scrollbar-none [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar-track]:hidden [&::-webkit-scrollbar-thumb]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
                      <div>
                        <span className="block font-mono text-xs text-zinc-400 font-bold uppercase tracking-wider mb-1">Diagnosing Agent Module</span>
                        <span className="inline-block px-3 py-1.5 bg-zinc-100 rounded-lg text-sm font-mono text-[#1b253c] font-bold">
                          {activeLog.module}
                        </span>
                      </div>

                      <div>
                        <span className="block font-mono text-xs text-zinc-400 font-bold uppercase tracking-wider mb-1">Maintenance & Action Details</span>
                        <p className="text-sm text-zinc-700 leading-relaxed font-sans bg-[#FAF9F5] p-5 rounded-2xl border border-zinc-150">
                          {activeLog.description}
                        </p>
                      </div>

                      {isFirstLog && viewMode === "pdf" && activeLog.pdfUrl && (
                        <div className="bg-[#FAF9F5] rounded-2xl border border-zinc-150 p-5">
                          <div className="flex items-center justify-between mb-2">
                            <span className="block font-mono text-xs text-zinc-400 font-bold uppercase tracking-wider">Attached Document</span>
                            <button
                              onClick={() => setExpandedView("pdf")}
                              className="flex items-center gap-1 text-[10px] font-mono font-bold text-[#1b253c] hover:text-[#f97316] uppercase tracking-wider transition-colors cursor-pointer"
                            >
                              <Maximize2 className="w-3 h-3" />
                              Pop Out
                            </button>
                          </div>
                          <div className="flex items-center gap-3 p-4 bg-white rounded-xl border border-zinc-200">
                            <FileText className="w-8 h-8 text-[#f97316] shrink-0" />
                            <div className="flex-1 min-w-0">
                              <span className="block text-sm font-bold text-[#1b253c] truncate">ai_hackathon_problem_statement.pdf</span>
                              <span className="block text-xs font-mono text-zinc-400">AI Hackathon Round 2 - Problem Statement</span>
                            </div>
                            <span className="text-[10px] font-mono text-zinc-400 bg-zinc-100 px-2 py-1 rounded-md">Source</span>
                          </div>
                          <div className="mt-3 p-4 bg-white rounded-xl border border-zinc-200 min-h-[180px] flex items-center justify-center">
                            <iframe
                              src={activeLog.pdfUrl}
                              className="w-full h-[400px] rounded-lg border-0"
                              title="PDF Preview"
                            />
                          </div>
                        </div>
                      )}

                      {isFirstLog && viewMode === "online" && activeLog.onlineContent && (
                        <div className="bg-[#FAF9F5] rounded-2xl border border-zinc-150 p-5">
                          <div className="flex items-center justify-between mb-2">
                            <span className="block font-mono text-xs text-zinc-400 font-bold uppercase tracking-wider">Online Version</span>
                            <button
                              onClick={() => setExpandedView("online")}
                              className="flex items-center gap-1 text-[10px] font-mono font-bold text-[#1b253c] hover:text-[#f97316] uppercase tracking-wider transition-colors cursor-pointer"
                            >
                              <Maximize2 className="w-3 h-3" />
                              Pop Out
                            </button>
                          </div>
                          <div className="flex items-center gap-3 p-4 bg-white rounded-xl border border-zinc-200 mb-3">
                            <FileCode className="w-8 h-8 text-emerald-600 shrink-0" />
                            <div className="flex-1 min-w-0">
                              <span className="block text-sm font-bold text-[#1b253c] truncate">tata_steel_ai_hackathon_problem_statement.md</span>
                              <span className="block text-xs font-mono text-zinc-400">Markdown Document</span>
                            </div>
                            <span className="text-[10px] font-mono text-zinc-400 bg-zinc-100 px-2 py-1 rounded-md">Online</span>
                          </div>
                          <div className="p-4 bg-white rounded-xl border border-zinc-200 max-h-[300px] overflow-y-auto scrollbar-none [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar-track]:hidden [&::-webkit-scrollbar-thumb]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
                            <div className="text-xs text-zinc-700 leading-relaxed prose prose-sm max-w-none [&_h1]:text-lg [&_h1]:font-black [&_h2]:text-base [&_h2]:font-black [&_h3]:text-sm [&_h3]:font-bold [&_ul]:list-disc [&_ul]:pl-4 [&_li]:mb-0.5 [&_strong]:font-bold">
                              <ReactMarkdown>{activeLog.onlineContent}</ReactMarkdown>
                            </div>
                          </div>
                        </div>
                      )}

                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <span className="block font-mono text-xs text-zinc-400 font-bold uppercase tracking-wider mb-1">Repair Operator</span>
                          <span className="block text-sm font-bold text-zinc-800">{activeLog.operator}</span>
                        </div>
                        <div>
                          <span className="block font-mono text-xs text-zinc-400 font-bold uppercase tracking-wider mb-1">Post-Action Verdict</span>
                          <span className="block text-sm font-bold text-[#75864C]">{activeLog.verdict}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Expanded View Modal */}
      {expandedView && activeLog && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-8 animate-in fade-in duration-200">
          <div className="bg-white border border-zinc-200/80 rounded-3xl w-full max-w-5xl max-h-[90vh] flex flex-col relative shadow-2xl animate-in fade-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between p-6 border-b border-zinc-200">
              <div className="flex items-center gap-3">
                {expandedView === "pdf" ? (
                  <FileText className="w-5 h-5 text-[#f97316]" />
                ) : (
                  <FileCode className="w-5 h-5 text-emerald-600" />
                )}
                <span className="font-mono text-sm font-bold text-zinc-800">
                  {expandedView === "pdf" ? "ai_hackathon_problem_statement.pdf" : "tata_steel_ai_hackathon_problem_statement.md"}
                </span>
              </div>
              <button
                onClick={() => setExpandedView(null)}
                className="p-2 rounded-xl hover:bg-zinc-100 transition-colors cursor-pointer"
              >
                <X className="w-5 h-5 text-zinc-500" />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-6 scrollbar-none [&::-webkit-scrollbar]:hidden [&::-webkit-scrollbar-track]:hidden [&::-webkit-scrollbar-thumb]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
              {expandedView === "pdf" && activeLog.pdfUrl && (
                <iframe
                  src={activeLog.pdfUrl}
                  className="w-full h-[75vh] rounded-lg border-0"
                  title="PDF Expanded View"
                />
              )}
              {expandedView === "online" && activeLog.onlineContent && (
                <div className="text-sm text-zinc-700 leading-relaxed prose prose-sm max-w-none [&_h1]:text-xl [&_h1]:font-black [&_h2]:text-lg [&_h2]:font-black [&_h3]:text-base [&_h3]:font-bold [&_ul]:list-disc [&_ul]:pl-5 [&_li]:mb-1 [&_strong]:font-bold">
                  <ReactMarkdown>{activeLog.onlineContent}</ReactMarkdown>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </ClickSpark>
  );
}
