"""
Seed sensor definitions and alarm thresholds for all 8 assets.
Values grounded in horizon_zephyr_summary.md operating envelopes.
"""
from apps.assets.models import Asset, SensorDefinition


SENSOR_REGISTRY = {
    "SRF": [
        {"sensor_name": "zone_1_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1150, "normal_max": 1250, "alert_threshold": 1135, "trip_threshold": 1120,
         "iso_standard_ref": "IEC 61511", "sampling_freq_hz": 0.1},
        {"sensor_name": "zone_2_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1150, "normal_max": 1250, "alert_threshold": 1135, "trip_threshold": 1120,
         "iso_standard_ref": "IEC 61511", "sampling_freq_hz": 0.1},
        {"sensor_name": "zone_3_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1150, "normal_max": 1250, "alert_threshold": 1135, "trip_threshold": 1120,
         "iso_standard_ref": "IEC 61511", "sampling_freq_hz": 0.1},
        {"sensor_name": "zone_4_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1150, "normal_max": 1250, "alert_threshold": 1135, "trip_threshold": 1120,
         "iso_standard_ref": "IEC 61511", "sampling_freq_hz": 0.1},
        {"sensor_name": "zone_5_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1150, "normal_max": 1250, "alert_threshold": 1135, "trip_threshold": 1120,
         "iso_standard_ref": "IEC 61511", "sampling_freq_hz": 0.1},
        {"sensor_name": "zone_6_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1150, "normal_max": 1250, "alert_threshold": 1135, "trip_threshold": 1120,
         "iso_standard_ref": "IEC 61511", "sampling_freq_hz": 0.1},
        {"sensor_name": "slab_temp_out", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 1180, "normal_max": 1240, "alert_threshold": 1150, "trip_threshold": 1100,
         "iso_standard_ref": "", "sampling_freq_hz": 0.2},
        {"sensor_name": "gas_flow", "sensor_type": "flow", "unit": "Nm³/hr",
         "normal_min": 5000, "normal_max": 15000, "alert_threshold": 4500, "trip_threshold": 3500,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
        {"sensor_name": "o2_pct", "sensor_type": "concentration", "unit": "%",
         "normal_min": 1.5, "normal_max": 2.5, "alert_threshold": 1.2, "trip_threshold": 0.8,
         "iso_standard_ref": "IEC 61508", "sampling_freq_hz": 1.0},
        {"sensor_name": "beam_stroke", "sensor_type": "position", "unit": "mm",
         "normal_min": 0, "normal_max": 300, "alert_threshold": None, "trip_threshold": None,
         "iso_standard_ref": "", "sampling_freq_hz": 2.0},
        {"sensor_name": "air_fuel_ratio", "sensor_type": "concentration", "unit": "ratio",
         "normal_min": 1.05, "normal_max": 1.15, "alert_threshold": 1.02, "trip_threshold": 1.0,
         "iso_standard_ref": "IEC 61508", "sampling_freq_hz": 1.0},
    ],
    "HHPD": [
        {"sensor_name": "header_pressure", "sensor_type": "pressure", "unit": "bar",
         "normal_min": 380, "normal_max": 400, "alert_threshold": 375, "trip_threshold": 350,
         "iso_standard_ref": "ISO 17359", "sampling_freq_hz": 2.0},
        {"sensor_name": "flow_rate", "sensor_type": "flow", "unit": "L/min",
         "normal_min": 4500, "normal_max": 5500, "alert_threshold": 4000, "trip_threshold": 3500,
         "iso_standard_ref": "", "sampling_freq_hz": 2.0},
        {"sensor_name": "ae_intensity_20khz", "sensor_type": "acoustic", "unit": "dB",
         "normal_min": -60, "normal_max": -30, "alert_threshold": -20, "trip_threshold": -10,
         "iso_standard_ref": "ISO 13373-3", "sampling_freq_hz": 10.0},
        {"sensor_name": "filter_delta_p", "sensor_type": "pressure", "unit": "bar",
         "normal_min": 0, "normal_max": 2.0, "alert_threshold": 3.0, "trip_threshold": 5.0,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
        {"sensor_name": "pump_vibration_rms", "sensor_type": "vibration", "unit": "mm/s",
         "normal_min": 0, "normal_max": 4.5, "alert_threshold": 4.5, "trip_threshold": 7.1,
         "iso_standard_ref": "ISO 10816-3", "sampling_freq_hz": 5.0},
    ],
    "FS": [
        {"sensor_name": "rolling_force_f1", "sensor_type": "force", "unit": "MN",
         "normal_min": 10, "normal_max": 20, "alert_threshold": 22, "trip_threshold": 25,
         "iso_standard_ref": "", "sampling_freq_hz": 10.0},
        {"sensor_name": "vibration_rms_f1", "sensor_type": "vibration", "unit": "mm/s",
         "normal_min": 0, "normal_max": 4.5, "alert_threshold": 4.5, "trip_threshold": 7.1,
         "iso_standard_ref": "ISO 10816-3", "sampling_freq_hz": 10.0},
        {"sensor_name": "bpfo_amplitude_f1", "sensor_type": "vibration", "unit": "dB",
         "normal_min": -50, "normal_max": -28, "alert_threshold": -20, "trip_threshold": -12,
         "iso_standard_ref": "ISO 13373-3", "sampling_freq_hz": 10.0},
        {"sensor_name": "sideload_f1", "sensor_type": "force", "unit": "kN",
         "normal_min": 200, "normal_max": 500, "alert_threshold": 600, "trip_threshold": 700,
         "iso_standard_ref": "", "sampling_freq_hz": 5.0},
        {"sensor_name": "spindle_torque_f1", "sensor_type": "torque", "unit": "kNm",
         "normal_min": 500, "normal_max": 3000, "alert_threshold": 3200, "trip_threshold": 3500,
         "iso_standard_ref": "", "sampling_freq_hz": 5.0},
        {"sensor_name": "gap_position_f1", "sensor_type": "position", "unit": "mm",
         "normal_min": 0, "normal_max": 50, "alert_threshold": None, "trip_threshold": None,
         "iso_standard_ref": "", "sampling_freq_hz": 10.0},
        {"sensor_name": "housing_temp_f1", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 20, "normal_max": 60, "alert_threshold": 75, "trip_threshold": 90,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
    ],
    "HAGCC": [
        {"sensor_name": "gap_position", "sensor_type": "position", "unit": "mm",
         "normal_min": 0, "normal_max": 50, "alert_threshold": None, "trip_threshold": None,
         "iso_standard_ref": "", "sampling_freq_hz": 100.0},
        {"sensor_name": "oil_pressure", "sensor_type": "pressure", "unit": "bar",
         "normal_min": 250, "normal_max": 350, "alert_threshold": 230, "trip_threshold": 200,
         "iso_standard_ref": "", "sampling_freq_hz": 10.0},
        {"sensor_name": "bypass_flow", "sensor_type": "flow", "unit": "L/min",
         "normal_min": 0, "normal_max": 1.0, "alert_threshold": 2.0, "trip_threshold": 5.0,
         "iso_standard_ref": "ISO 19973", "sampling_freq_hz": 2.0},
        {"sensor_name": "hysteresis_deviation_um", "sensor_type": "position", "unit": "μm",
         "normal_min": 0, "normal_max": 30, "alert_threshold": 50, "trip_threshold": 100,
         "iso_standard_ref": "", "sampling_freq_hz": 100.0},
        {"sensor_name": "oil_particle_count_4um", "sensor_type": "concentration", "unit": "cnt/mL",
         "normal_min": 0, "normal_max": 1000, "alert_threshold": 5000, "trip_threshold": 10000,
         "iso_standard_ref": "ISO 4406", "sampling_freq_hz": 0.01},
    ],
    "APT": [
        {"sensor_name": "hcl_free_pct", "sensor_type": "concentration", "unit": "%",
         "normal_min": 12.0, "normal_max": 18.0, "alert_threshold": 10.0, "trip_threshold": 8.0,
         "iso_standard_ref": "OSHA 1910.119", "sampling_freq_hz": 0.1},
        {"sensor_name": "tank_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 65, "normal_max": 85, "alert_threshold": 90, "trip_threshold": 95,
         "iso_standard_ref": "OSHA 1910.119", "sampling_freq_hz": 0.5},
        {"sensor_name": "fecl2_gpl", "sensor_type": "concentration", "unit": "g/L",
         "normal_min": 0, "normal_max": 120, "alert_threshold": 120, "trip_threshold": 150,
         "iso_standard_ref": "OSHA 1910.119", "sampling_freq_hz": 0.05},
        {"sensor_name": "rinse_flow", "sensor_type": "flow", "unit": "m³/hr",
         "normal_min": 5, "normal_max": 30, "alert_threshold": 3, "trip_threshold": 1,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
        {"sensor_name": "tank_wall_thickness_mm", "sensor_type": "position", "unit": "mm",
         "normal_min": 10, "normal_max": 20, "alert_threshold": 7, "trip_threshold": 5,
         "iso_standard_ref": "NACE SP0169", "sampling_freq_hz": 0.0003},
    ],
    "TCMS": [
        {"sensor_name": "rolling_force", "sensor_type": "force", "unit": "MN",
         "normal_min": 8, "normal_max": 20, "alert_threshold": 22, "trip_threshold": 25,
         "iso_standard_ref": "", "sampling_freq_hz": 10.0},
        {"sensor_name": "interstand_tension", "sensor_type": "force", "unit": "MPa",
         "normal_min": 50, "normal_max": 150, "alert_threshold": 160, "trip_threshold": 180,
         "iso_standard_ref": "", "sampling_freq_hz": 5.0},
        {"sensor_name": "emulsion_flow", "sensor_type": "flow", "unit": "L/min",
         "normal_min": 2000, "normal_max": 4000, "alert_threshold": 1500, "trip_threshold": 1000,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
        {"sensor_name": "emulsion_iron_ppm", "sensor_type": "concentration", "unit": "ppm",
         "normal_min": 0, "normal_max": 200, "alert_threshold": 300, "trip_threshold": 500,
         "iso_standard_ref": "", "sampling_freq_hz": 0.01},
        {"sensor_name": "emulsion_ph", "sensor_type": "concentration", "unit": "pH",
         "normal_min": 5.5, "normal_max": 6.5, "alert_threshold": 5.0, "trip_threshold": 4.5,
         "iso_standard_ref": "", "sampling_freq_hz": 0.1},
        {"sensor_name": "bpfo_amplitude_142hz", "sensor_type": "vibration", "unit": "dB",
         "normal_min": -60, "normal_max": -28, "alert_threshold": -20, "trip_threshold": -12,
         "iso_standard_ref": "ISO 13373-3", "sampling_freq_hz": 10.0},
        {"sensor_name": "chock_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 35, "normal_max": 65, "alert_threshold": 80, "trip_threshold": 90,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
    ],
    "CGP": [
        {"sensor_name": "pot_temp", "sensor_type": "temperature", "unit": "°C",
         "normal_min": 450, "normal_max": 462, "alert_threshold": 462, "trip_threshold": 470,
         "iso_standard_ref": "ISO 1461", "sampling_freq_hz": 0.5},
        {"sensor_name": "fe_in_zinc_pct", "sensor_type": "concentration", "unit": "%",
         "normal_min": 0, "normal_max": 0.03, "alert_threshold": 0.03, "trip_threshold": 0.05,
         "iso_standard_ref": "ISO 1461", "sampling_freq_hz": 0.02},
        {"sensor_name": "pot_level", "sensor_type": "position", "unit": "mm",
         "normal_min": 500, "normal_max": 800, "alert_threshold": 450, "trip_threshold": 400,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
        {"sensor_name": "pot_roll_torque", "sensor_type": "torque", "unit": "Nm",
         "normal_min": 50, "normal_max": 500, "alert_threshold": 600, "trip_threshold": 800,
         "iso_standard_ref": "", "sampling_freq_hz": 2.0},
        {"sensor_name": "inductor_power", "sensor_type": "power", "unit": "kW",
         "normal_min": 100, "normal_max": 800, "alert_threshold": None, "trip_threshold": None,
         "iso_standard_ref": "", "sampling_freq_hz": 1.0},
    ],
    "HPAK": [
        {"sensor_name": "air_pressure", "sensor_type": "pressure", "unit": "bar",
         "normal_min": 0.3, "normal_max": 1.2, "alert_threshold": 0.2, "trip_threshold": 0.1,
         "iso_standard_ref": "ISO 17359", "sampling_freq_hz": 2.0},
        {"sensor_name": "nozzle_distance_mm", "sensor_type": "position", "unit": "mm",
         "normal_min": 8, "normal_max": 20, "alert_threshold": 7, "trip_threshold": 5,
         "iso_standard_ref": "", "sampling_freq_hz": 2.0},
        {"sensor_name": "blower_current", "sensor_type": "current", "unit": "A",
         "normal_min": 20, "normal_max": 80, "alert_threshold": 90, "trip_threshold": 100,
         "iso_standard_ref": "", "sampling_freq_hz": 2.0},
        {"sensor_name": "header_pressure_drop_mbar", "sensor_type": "pressure", "unit": "mbar",
         "normal_min": 0, "normal_max": 60, "alert_threshold": 95, "trip_threshold": 150,
         "iso_standard_ref": "ISO 17359", "sampling_freq_hz": 2.0},
        {"sensor_name": "coating_weight_deviation_gm2", "sensor_type": "concentration",
         "unit": "g/m²", "normal_min": -5, "normal_max": 5, "alert_threshold": 8,
         "trip_threshold": 15, "iso_standard_ref": "ISO 1461", "sampling_freq_hz": 1.0},
    ],
}


def seed_sensor_definitions(asset: Asset) -> int:
    sensors = SENSOR_REGISTRY.get(asset.asset_type, [])
    created = 0
    for s in sensors:
        _, was_created = SensorDefinition.objects.get_or_create(
            asset=asset,
            sensor_name=s["sensor_name"],
            defaults=s,
        )
        if was_created:
            created += 1
    return created


def seed_alarm_thresholds(asset: Asset):
    """Alarm events are generated dynamically; this validates sensor defs have thresholds."""
    count = SensorDefinition.objects.filter(
        asset=asset,
        alert_threshold__isnull=False,
    ).count()
    return count
