"""Site-wide legend / glossary entries for Samvidhaan."""

GLOSSARY_ENTRIES = [
  {"term": "Remaining Useful Life", "shortForm": "RUL", "category": "Prediction", "definition": "Estimated operating time before equipment requires maintenance or replacement.", "isoRef": "ISO 13381-1"},
  {"term": "Root Cause Analysis", "shortForm": "RCA", "category": "Diagnostics", "definition": "Structured method to identify underlying causes of failures rather than symptoms.", "isoRef": "ISO 14224"},
  {"term": "Hydraulic Oil Cleanliness", "shortForm": "ISO 4406", "category": "Standards", "definition": "Particle contamination code for hydraulic fluids; critical for bearing and AGC cylinder life.", "isoRef": "ISO 4406"},
  {"term": "Vibration Severity", "shortForm": "ISO 10816", "category": "Standards", "definition": "Mechanical vibration evaluation on non-rotating parts for rotating machinery.", "isoRef": "ISO 10816-3"},
  {"term": "Slab Reheating Furnace", "shortForm": "SRF", "category": "Asset", "definition": "Thermal input stage reheating steel slabs before rolling.", "relatedAssets": ["SRF"]},
  {"term": "High-Pressure Descaler", "shortForm": "HHPD", "category": "Asset", "definition": "Removes mill scale from slab surface using high-pressure water jets.", "relatedAssets": ["HHPD"]},
  {"term": "Finishing Stands", "shortForm": "FS", "category": "Asset", "definition": "Rolling mill stands reducing thickness with high force and precision.", "relatedAssets": ["FS"]},
  {"term": "Hydraulic Automatic Gauge Control", "shortForm": "HAGCC", "category": "Asset", "definition": "Hydraulic cylinders controlling strip thickness during rolling.", "relatedAssets": ["HAGCC"]},
  {"term": "Acid Pickling Tanks", "shortForm": "APT", "category": "Asset", "definition": "Surface treatment removing oxide scale before cold rolling.", "relatedAssets": ["APT"]},
  {"term": "Tandem Cold Mill Stands", "shortForm": "TCMS", "category": "Asset", "definition": "Multi-stand cold reduction mill achieving final gauge.", "relatedAssets": ["TCMS"]},
  {"term": "Continuous Galvanizing Pot", "shortForm": "CGP", "category": "Asset", "definition": "Molten zinc bath applying protective coating to steel strip.", "relatedAssets": ["CGP"]},
  {"term": "High-Pressure Air Knives", "shortForm": "HPAK", "category": "Asset", "definition": "Controls zinc coating weight after galvanizing.", "relatedAssets": ["HPAK"]},
  {"term": "Predictive Maintenance", "shortForm": "PdM", "category": "Strategy", "definition": "Maintenance triggered by condition monitoring and ML forecasts rather than fixed intervals."},
  {"term": "Condition Monitoring", "shortForm": "CM", "category": "Strategy", "definition": "Continuous or periodic assessment of equipment health via sensors and analytics."},
  {"term": "Anomaly Detection", "shortForm": "AD", "category": "ML", "definition": "Statistical or ML technique flagging deviations from normal operating patterns."},
  {"term": "Remaining Life", "shortForm": "RL", "category": "Prediction", "definition": "Synonym for RUL in maintenance planning contexts."},
  {"term": "Lock Out Tag Out", "shortForm": "LOTO", "category": "Safety", "definition": "Safety procedure isolating energy sources before maintenance work.", "isoRef": "OSHA 1910.147"},
  {"term": "Standard Operating Procedure", "shortForm": "SOP", "category": "Documentation", "definition": "Step-by-step instructions for routine or corrective tasks."},
  {"term": "Bill of Materials", "shortForm": "BOM", "category": "Spares", "definition": "List of parts and quantities required for maintenance or assembly."},
  {"term": "Mean Time To Repair", "shortForm": "MTTR", "category": "KPI", "definition": "Average time to restore equipment after failure."},
  {"term": "Bustle Temperature Point", "shortForm": "BTP", "category": "Process", "definition": "Sintering process indicator for burn-through position on the strand."},
  {"term": "Iron Oxide in Sinter", "shortForm": "FeO", "category": "Process", "definition": "Chemical indicator of sinter reducibility and blast furnace permeability."},
  {"term": "Coke Oven Gas", "shortForm": "COG", "category": "Process", "definition": "By-product fuel gas from coke ovens used across the plant."},
  {"term": "Automatic Gauge Control", "shortForm": "AGC", "category": "Control", "definition": "Closed-loop thickness control during hot or cold rolling."},
  {"term": "Supervisory Control and Data Acquisition", "shortForm": "SCADA", "category": "Systems", "definition": "Plant-wide monitoring and control layer feeding telemetry to ATAL."},
  {"term": "Programmable Logic Controller", "shortForm": "PLC", "category": "Systems", "definition": "Industrial controller generating fault messages ingested by SANSAD."},
  {"term": "Maintenance Wizard", "shortForm": "MANAS", "category": "Product", "definition": "Natural-language AI assistant for diagnostics, RAG, and repair guidance."},
  {"term": "Steel Analytics & Notification Agent Dashboard", "shortForm": "SANSAD", "category": "Product", "definition": "Plant orchestration layer combining ML, LangGraph, and real-time alerts."},
  {"term": "Retrieval Augmented Generation", "shortForm": "RAG", "category": "AI", "definition": "LLM answers grounded in equipment manuals, SOPs, and maintenance logs."},
  {"term": "LangGraph Orchestration", "shortForm": "LangGraph", "category": "AI", "definition": "Multi-agent workflow running consolidation, tools, and report generation."},
  {"term": "Urgency Score", "shortForm": "US", "category": "Risk", "definition": "Composite 0–100 priority index from criticality, delay, spares, and lead time."},
  {"term": "Bottleneck Asset", "shortForm": "—", "category": "Risk", "definition": "Highest-ranked equipment limiting plant throughput or reliability."},
  {"term": "Digital Logbook", "shortForm": "DL", "category": "Reports", "definition": "Auto-drafted maintenance record from completed work orders or events."},
  {"term": "Abnormal Alert Report", "shortForm": "AAR", "category": "Reports", "definition": "Structured digest of active threshold breaches and anomaly events."},
  {"term": "Decision Summary", "shortForm": "DS", "category": "Reports", "definition": "Supervisor-facing prioritization brief across plant bottlenecks."},
  {"term": "Cross-Stage Correlation", "shortForm": "CSC", "category": "Diagnostics", "definition": "Links upstream process deviations to downstream mechanical failures."},
  {"term": "Horizon Foundry", "shortForm": "F1", "category": "Factory", "definition": "Hot rolling complex — SRF through HAGCC production sequence."},
  {"term": "Zephyr Sinter", "shortForm": "F2", "category": "Factory", "definition": "Cold rolling and coating line — APT through HPAK sequence."},
]
