# Generated by Django 6.0.6 on 2026-06-14 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='users.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.factory'),
        ),
        migrations.AddField(
            model_name='sensordefinition',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='sparespart',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='assets.asset'),
        ),
        migrations.AlterUniqueTogether(
            name='factory',
            unique_together={('org', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='sensordefinition',
            unique_together={('asset', 'sensor_name')},
        ),
    ]
