# Generated by Django 6.0.6 on 2026-06-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='llm_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ml.mlprediction'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['asset', 'created_at'], name='reports_mai_asset_i_334504_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['risk_level', 'created_at'], name='reports_mai_risk_le_75b955_idx'),
        ),
    ]
