# Generated by Django 6.0.6 on 2026-06-14 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('asset_id', models.UUIDField(blank=True, null=True)),
                ('args', models.JSONField(default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('rejected', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
