# Generated by Django 6.0.6 on 2026-06-14 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_chatmessage_reasoning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=8)),
                ('traits_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='agents.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents_chat_message_feedback',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='uniq_chat_msg_feedback_per_user')],
            },
        ),
    ]
