# Generated by Django 6.0.6 on 2026-06-14 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('confirm', 'Confirm'), ('correct', 'Correct'), ('reject', 'Reject')], max_length=10)),
                ('corrected_values', models.JSONField(blank=True, default=dict)),
                ('chroma_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_feedback',
            },
        ),
    ]
