# Generated by Django 6.0.6 on 2026-06-14 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generator_name', models.CharField(max_length=100)),
                ('rows_generated', models.PositiveIntegerField(default=0)),
                ('fault_events_injected', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_runs', to='assets.asset')),
            ],
            options={
                'db_table': 'synthetic_generation_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
